travis:
  secure:
    BINSTAR_TOKEN: iYG+v+QaG8U8ruL6RZFjWmjLHHwRH7j1Kh/7bTr/SpUBzhfxqh9GO2UtRTNhLfYSAsgQ4aa8cu+98MZyUVqRJxFqYaSUWOXI/egosuow0ghpPTAY7swRtgQ9AtNtW57o9zwjDD1BbdEJ+w+HcfFY31S4auThXiGNEk9Tl1PtE/xvhcmRk8KDMjVIvqeDdtkZzdpEOrVVrjybgfrlb40j/wp387d7fA22lMT9oelRCeiuuGdTFz3ZFq09g/foeOJgEhmKButGBZ9E4AC7ktZYE1RxkQ5WxJTaXGfNRV4vdDDZ4XJ58TV7JQH/scVJU26Fiu1W5flaYJoUWNyaKUxDnErDDq/rfNVNGL6MrN7PFgqUsYLGgxXsGjCIkCP+7n/8Ejm6K/PrL59RsRW9sSD50yxVD5hzgdAAgT5wy6LT8lpRcEsas2wA0SFGsXQAZ5lCCsFnlGzZ9yXmm85llhTatvGUiFhdRQH8EPw+Iz5BNRshgAn2NMrN5rUsqEgkpcALy9pLik7P7FYHMAxyZPPCSWBBvCKmoHg2MuyaIFoZt46VP6j8/Y2GpSHW5S8TFvpMgRlCzn+HPA9wtj73r84z7ingG2LOAYjjWKt/UGdA8/A+IhC9QTwRva9zn0htY7kAyiO/5eKsrYqug5JPE16dGBv5GnNXLRmVUthKNQl1NBI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
