travis:
  secure:
    BINSTAR_TOKEN: JwrvsjE1VVLzt0BEX92hnI3aFdwic9feZV01QWB17XG7O53ddnK8uLUJOjV8Rhh6Mk1NN3sAMCc8Y/XQpRBNZgg5NOYMa2qeEfwq5PZpG+Nvrqdyf8DnW+qLhJ7HQhkdOZHVlRNPFg0k89Vj+PLGLaHU9ORa7ppHWV8aDsy36A7ibPLjMSONqW4bTrSe4fTI5nsqbNGYLhgI05guQ1CufBgQK7Ug5lWkOsfD4cQbc+QfWhFOA2/Ivt3GEKkpfxhtiv+XYqsPm97W35XS3aDvdebCapAOZw+hl0FXbFIRM0Y1a63Qjl8StCw+aKtj09dvZTbbvEGkwucwq0B7r94nb4v/VgUqZT8U7CmkZN3AFAioLhwGjwJLG3zbAV3HZyBY4qitSbYpMEbf+C8InwmDG6uzot143ybYEO8QxJ3iaki0jXE9jyFsPLzRGhXDXj7Oy/zPh/C/oL5YLnLkdKRqSxNthci2TOjVwoXQ76zq4vlKL6/g+7O39FCYe8+LLqH183G5zHRLo4rUo/eImrAA/0gV5snZAKvQQhplCvWgk2ehg97i+O1SjsD+icA63fAV2bXguqcDQ5fw/KSERwX9tEaKj40XN+YiIeZYmSJEHD/PM68p3WU+mUxHYjRYbYGnmhBE0FG0UMsJ3qYqTslgSViiqrsRoUuWMryi2F85Eyg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
