travis:
  secure:
    BINSTAR_TOKEN: X8BRVyKtvkf6/ApxnFp+C2pDGldPg+qXi4JNBDbMBkkNoX51wtvgDLEEWqARv2ROJ6jDIHtDb/xnPsrROXIKXucxj1PqClhwojGuusS29eII6pzRZ97p9scph0Il/xyt4P80Jj+zAvvIAOlxlaBCLA67lBnzHhz/ZplXrZRhrW5bI24ppkZ3wgrV3ViQm+fRKH/WCjIbgTY8tU8A6o8ZLCfk5Dt0ZEkZuTPA+qUA6YuTlbvDwiwzUhHpbK1w+pRB6CsK/Ouf0S2lUVbo1SkIEIRLUdm/VyXzNXhd4tpylV6O+wrLagjjq9TBqWWWiEjhf6V8SXkJbzAsSlJR2yLNot8dZsbdFUXSefDdJ/fTs09PJbpIOs6+r+SPoIeoey18CrQmroDIPy8keNFBoND6SXRgCewNnswtnzfKv7ml8IsimYqtlfk0hDq3LMzDcaUBoZgG3a3bsWiU2SHBZODNocIVEEPztQ0V/DUncW0zNDaN8OMmThJJcFGisOZtW1+Gksk8t82C4/qYxUWg8VZd5nBJBEhL9Nss3BGkzW8abssIvLIxGinYrL7fbNa3p7rqJIrKgVgfFWNd08Fjq+NQpMquoCgkOV83OjG+AEvc7b00T57hHX67zYNXW4zAIwylMWU7OTTdyjdJF2HNaukLEix0SglnidDDpKPsigB0Ehc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
