travis:
  secure:
    BINSTAR_TOKEN: FVp1WEJ+4wqavKS87gKeDwh1qpVunVJYjolmfCcCBWk1NAuO5rBs1Z0+yYYIpHEpu/gFdTwAgxavuviaLLRGiSzHpEH74bp5uzmmhdydLPnZUsgOr/Glbpt8sEL0uskLu22x8X1ZNLskqfyhIVQ8DzbWIA/mPWWawcXBSPvcwYwR3/iIMfOKlLfU9AX8OlziqpAZh1bwwnapzTT53mlqSyxa+g9EkHHykq0mHkCng7sXxh2zXnfpQEPyT53RbF7yAUqpwjOADeEBS8b0RXxyGZH5iHMPqAo+yp70ZR9ZEJaH6+5hMXlbjdFpoC6cshraUBINCBH2nB+n5HNgYxlXA4dliF9vcazPGCuf6cQTdWL49AhVEArXFKtWNLoyPtHM3wfEMESN0V0dSiCy10jLsOtI8oHzJ2N4ncQrBRovyxdR/7/uR8fSOFekAm0kpLolvK9wbyFYqNU/WuW/obeoEiJ56K2hUXrEkZzpTc2mBV1NAHrcGrDROgKUBYlhqmK6C1RcXx8KA2Q5D2NFA37AviVpzwxgYNa9BQ7jqO2eNqUCBD+4M58fAoGT8BPwBc52s2mZr0zJ4j+u3AV4dJc2FRzAARH5DS6ESoiSKLGdkO9I3Q/AR7wkX+lwLyNN2uiFn4rKR8j5mdnifDOBSPfHOvsu31Kis4MWxKtpJeMaJsA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
